# LOCAL DEVELOPMENT USE ONLY
version: '3.8'

services:
  pgsql-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: AC-dev
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  pgsql-adminer-console:
    image: adminer
    restart: always
    ports:
      - 8080:8080
