# LOCAL DEVELOPMENT USE ONLY
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: AC-dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080